language: python
python:
  - 3.7
install:
  - python setup.py install
  - pip install codecov
  - pip install numpy==1.17.2
  - pip install install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
script:
  -  chmod +x setup.py
  - ./setup.py test
after_success:
  - codecov